/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#1A237E',
        onPrimary: '#FFFFFF',
        primaryContainer: '#DEE0FF',
        onPrimaryContainer: '#00105C',
        secondary: '#5B5D72',
        onSecondary: '#FFFFFF',
        secondaryContainer: '#DFE1F9',
        onSecondaryContainer: '#181A2E',
        tertiary: '#77536D',
        onTertiary: '#FFFFFF',
        tertiaryContainer: '#FFD7F1',
        onTertiaryContainer: '#2D1228',
        error: '#BA1A1A',
        onError: '#FFFFFF',
        errorContainer: '#FFDAD6',
        onErrorContainer: '#410002',
        background: '#FEFBFF',
        onBackground: '#1B1B1F',
        surface: '#FEFBFF',
        onSurface: '#1B1B1F',
        surfaceVariant: '#E3E1EC',
        onSurfaceVariant: '#46464F',
        outline: '#767680',
        outlineVariant: '#C7C5D0',
        surfaceContainerLow: '#F5F2F7',
        surfaceContainer: '#EFEDF1',
        surfaceContainerHigh: '#E9E7EC',
        inverseSurface: '#303034',
        inverseOnSurface: '#F3F0F4',
      },
      fontFamily: {
        sans: ["System", "sans-serif"],
      },
      borderRadius: {
        "2xl": "16px",
        "3xl": "24px",
      },
    },
  },
  plugins: [],
};
